# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f867641f833c02e0a64214f8299d6745d08a8d9f6ecfc8f088b8d7db9c42a99a27e58a524c40bb2607e7a984543c6e1ff973d354d0354db74caeb51478655d55

test:
  secret_key_base: d00da6e6d0793babc2641caa9e717539592bf6caa3d91e90821b30eb0d2bb23bb56270b8202f13f7111d20521bca956f5bbb9ec07f499342e52e827a14bb6eaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
